<?php
    $lang['number']   = 'Invoice ID';
    $lang['date']     = 'Tanggal Pemesanan';
    $lang['time']     = 'Billing time';
    $lang['due']      = 'Status Pembayaran';
    $lang['to']       = '';
    $lang['from']     = 'Detail';
    $lang['product']  = 'Item';
    $lang['qty']      = 'Qty';
    $lang['price']    = 'Price';
    $lang['discount'] = 'Discount';
    $lang['vat']      = 'Vat';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
